title: "Stuyvesant Political Review"
description: "Stuyvesant High School’s nonpartisan political magazine and website."
baseurl: ""
url: "stuypoli.gitlab.io" 

# Markdown settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Collections
collections:
  posts:
    output: true
